program choice
  ! 
  ! CHOICE = CHalmers university nOIse CodE
  ! Programmer: Tomas Grönstedt. Program based on the NoPred code developed by David Carlsson and Lars Ellprant supervised by Richard Avellán.  
  !
  ! v1.0 17.04.01  Date written.
  !
  !
  use choice_interf
  use choice_read_and_write
  !
  implicit none
  !
  character(len=32), dimension(3) :: operating_point ! Maximum number of points is three (Take-off, Cutback or Approach). Code also works for single point/single trajectory.
  logical :: traj_perf, gen_sources, ground_refl, spherical_spr, atm_atten, traj_preparse
  integer :: i, no_operating_points
  
! Read external files using the "craw" module. The "craw" is abbreviation for = "choice_read_and_write.f90" module. 
! External text files will be transferred to the character arrays: perf_file, dim_file, weight_file, noise_file
! Additionally dim_file will be parsed to define n_modules and modules(:) specifying the engine architecture.
  call read_external_files_craw() 
! 
! Transfer data read into craw to choice (choice_interf)
  call set_configuration_choice(get_n_modules_craw(),get_configuration_craw(get_n_modules_craw())) ! set n_modules & modules in choice by transfer
  call set_weight_choice(get_n_weight_lines_craw(),get_weightFile_craw(get_n_weight_lines_craw())) ! transfer weightAircraft.txt-data (design data generated by weico)
  call set_noise_choice(operating_point,no_operating_points,traj_perf,traj_preparse,gen_sources,ground_refl,spherical_spr, & 
      & atm_atten,get_n_noise_lines_craw(),get_noiseFile_craw(get_n_noise_lines_craw())) ! transfer inputNoise.txt-data 
  if( traj_preparse ) call preparse_trajectories(traj_preparse,traj_perf,no_operating_points,operating_point) ! execution stops after preparse. Must set false to proceed to calculations.
  !
  call get_version_num('choiceOutput.txt')
  !
  do i = 1,3! no_operating_points
! read x, y, Va, alpha from trajectory file (Cutback.txt, Take-off.txt or Approach.txt).      
    call set_trajectory_subr(i,operating_point(i))   ! Compute r, clgr and xsi, time
!
    call calc_noise_points(i)
    
  end do

  ! establish ICAO certification limits for given mass and number of engines. 
  call certificationLimits(get_no_engines(),get_MTOW())
  
contains   
   subroutine calc_noise_points(i)
     integer, intent(in) :: i
     
     if( .not. traj_perf ) call set_rotational_speeds_choice() ! estimate absolute speeds from relative rotating speeds (from performance) using several points      
   
     call set_performance_choice(i,traj_perf,trim(operating_point(i))) ! transfer performance (from performanceResults.txt) in particular point.

     call compute_noise_sources(gen_sources,trim(operating_point(i)))

     call interpolate_to_t_source()

     call compute_flight_effects(i,ground_refl,spherical_spr,atm_atten,trim(operating_point(i)))
     
     
     
         call compute_certification_data()
     
     
     
     call save_noise_points('choiceOutput.txt',trim(operating_point(i)))
     
     call deallocate_module_arrays() ! deallocate component storage arrays 

   end subroutine calc_noise_points
end program choice
